### ISSUE TITLE
Strange results with shared weights

### ISSUE THREAD

**Issue by MBaltz** [wdayang/CTformer#3]
Hello @wdayang. 

Using the [shared weights](https://github.com/wdayang/CTformer/issues/2) I'm getting strange results. Do you know what this is?
![image](https://user-images.githubusercontent.com/25617786/155250489-abd5a23a-4d9f-4f54-93f1-fbc3abd3166d.png)

This is the command executed:
```bash
$ python3 T2T_main.py --mode test --test_iters=540064 --saved_path=/home/baltz/dados/mayo_TEDNET_dataset/ponto_NPY --save_path=/home/baltz/dados/execs_CTformer/atual
````
When I used my weights treined for 200 epoch, i got better results. It is stranger.

I tested it in Python 3.9 and 3.7 version.  With torch 1.9 and 1.5.

---

_Also I got this problem, but is already solved: [link](https://github.com/knazeri/edge-connect/issues/121#issuecomment-1048382609)_

**Comment by MBaltz** [comment]
**Solution:**
This issue was caused because of the wrong process of loading the weights.

I solved this and wrote my solution as an answer in this other GitHub Issue:
https://github.com/knazeri/edge-connect/issues/121#issuecomment-1048382609

**Comment by wdayang** [comment]
Hi Mateus,

Thanks for the update, sorry for just seeing your email. I actually did not
encounter this problem. It's great that you pointed out the potential
problem and solved it by yourself. Thanks

Best,
Dayang
