### ISSUE TITLE
Strange results with artifacts

### ISSUE THREAD

**Issue by Joker-ZXR** [wdayang/CTformer#6]
Hi, thank you for your valued work!
I recently tried to use your network structure for medical image generation tasks. The model does not load pre-training weights, but produces strange results with artifacts. Have you encountered this situation? I am looking forward to your reply！
![图片](https://user-images.githubusercontent.com/40375714/162947973-e91f48b5-f965-44d5-aac1-f7a88c60e773.png)

**Comment by wdayang** [comment]
Hi, @Joker-ZXR Thanks for your interest in our work. 

Did you mean you loaded the weights from pre-trained models? I think you need to train or load pre-trained weights to get reasonable results. If you have loaded the pre-trained weights. You need to use our latest code. We made some minor modifications to the first-version code. Feel free to update with me. 

Best,
Dayang

**Comment by Joker-ZXR** [comment]
> 

Thank you for your prompt reply. I did not load the pre-training model because I wanted to try to use this framework for image generation tasks. I did a supervised generation task, but I found this artifact on the result. What do you think might account for that? Is it because of the model itself?
I find that the structure of your model is to generate noise image at last, and then subtract the noise image from the original image. Have you tried to directly generate the de-noised image?
Is the model only capable of reconstructing itself, rather than generating new images?
Looking forward to your reply. Thank you very much！

**Comment by wdayang** [comment]
Hi @Joker-ZXR , I am sorry I am not very familiar with generation tasks. Are you using our model in GAN as a generator or something? Do you want to share some of your model codes, I can have a look. 

Yes, our current model learns the noise patterns rather than the de-noised image itself. But I also tried to take away the residual shortcut. It should also be able to generate the de-noised image. 

I think the design of the model is indeed a reconstruction of the original image pixels. I am not sure whether it's able to generate unseen images from random noise.

Best,
Dayang

**Comment by Joker-ZXR** [comment]
Thank you for your reply @wdayang. This is my model code.I made some modifications to the model. The input images of the task were T1 sequences of MRI, and the objective was to generate T1c sequences of MRI and CT.
`
class encoder(nn.Module):
    """
    CTformer encoding module
    """
    def __init__(self, img_size=256, tokens_type='performer', in_chans=1, embed_dim=256, token_dim=64, kernel=32, stride=32):
        super(encoder, self).__init__()

        if tokens_type == 'transformer':
            print('adopt transformer encoder for tokens-to-token')
            self.soft_split0 = nn.Unfold(kernel_size=(7, 7), stride=(4, 4), padding=(2, 2))
            self.soft_split1 = nn.Unfold(kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
            self.soft_split2 = nn.Unfold(kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))

            self.attention1 = Token_transformer(dim=in_chans*7*7, in_dim=token_dim, num_heads=1, mlp_ratio=1.0)
            self.attention2 = Token_transformer(dim=token_dim*3*3, in_dim=token_dim, num_heads=1, mlp_ratio=1.0)
            self.project = nn.Linear(token_dim * 3 * 3, embed_dim)

        elif tokens_type == 'performer':
            # print('adopt performer encoder for tokens-to-token')
            self.soft_split0 = nn.Unfold(kernel_size=(7, 7), stride=(4, 4), padding=(2, 2))
            self.soft_split1 = nn.Unfold(kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
            self.soft_split2 = nn.Unfold(kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))

            self.attention1 = Token_performer(dim=in_chans*7*7, in_dim=token_dim, kernel_ratio=0.5)
            self.attention2 = Token_performer(dim=token_dim*3*3, in_dim=token_dim, kernel_ratio=0.5)
            self.project = nn.Linear(token_dim * 3 * 3, embed_dim)
        self.num_patches = (img_size // (4 * 2 * 2)) * (img_size // (4 * 2 * 2))  # there are 3 sfot split, stride are 4,2,2 seperately
        
    def forward(self, x):  # input[1,1,256,256]
        # Tokenization
        x = self.soft_split0(x)   # [1, 7*7, 64*64])
        
        # CTformer module A
        x = self.attention1(x.transpose(1, 2))  # [1, 64*64, 7*7] ->[1, 64*64, 64]
        t1_1 = x  # [1, 64*64, 64]
        B, new_HW, C = x.shape
        x = x.transpose(1,2).reshape(B, C, int(np.sqrt(new_HW)), int(np.sqrt(new_HW))) # [1, 64, 64, 64]
        x = torch.roll(x, shifts=(2, 2), dims=(2, 3))  # shift some position
        x = self.soft_split1(x)   # [1, 3*3*64=576, 64*64=4096]
        
        # CTformer module B
        x = self.attention2(x.transpose(1, 2))  # [1, 32*32, 3*3*64] ->[1, 32*32, 64]
        t1_2 = x  # [1, 32*32, 64]
        B, new_HW, C = x.shape
        x = x.transpose(1, 2).reshape(B, C, int(np.sqrt(new_HW)), int(np.sqrt(new_HW))) # [1, 64, 32, 32]
        x = torch.roll(x, shifts=(2, 2), dims=(2, 3))  # shift back position
        x = self.soft_split2(x)    # [1, 3*3*64=576, 16*16=256]

        x = self.project(x.transpose(1, 2))  # no projection[1,16*16=256, 64]
        return x, t1_1, t1_2  # res0,res2
    
class decoder_t1c(nn.Module):
    """
    CTformer decoding module
    """
    def __init__(self, img_size=256, tokens_type='performer', in_chans=1, embed_dim=256, token_dim=64, kernel=32, stride=32):
        super(decoder_t1c, self).__init__()

        if tokens_type == 'transformer':
            print('adopt transformer encoder for tokens-to-token')
            self.soft_split0 = nn.Fold((256,256),kernel_size=(7, 7), stride=(4, 4), padding=(2, 2))
            self.soft_split1 = nn.Fold((64,64),kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
            self.soft_split2 = nn.Fold((32,32),kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))

            self.attention1 = Token_transformer(dim=token_dim, in_dim=in_chans*7*7, num_heads=1, mlp_ratio=1.0)
            self.attention2 = Token_transformer(dim=token_dim, in_dim=token_dim*3*3, num_heads=1, mlp_ratio=1.0)
            self.project = nn.Linear(embed_dim,token_dim * 3 * 3)
        elif tokens_type == 'performer':
            #print('adopt performer encoder for tokens-to-token')
            self.soft_split0 = nn.Fold((256,256),kernel_size=(7, 7), stride=(4, 4), padding=(2, 2))
            self.soft_split1 = nn.Fold((64,64),kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
            self.soft_split2 = nn.Fold((32,32),kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))

            self.attention1 = Token_performer(dim=token_dim, in_dim=in_chans*7*7, kernel_ratio=0.5)
            self.attention2 = Token_performer(dim=token_dim, in_dim=token_dim*3*3, kernel_ratio=0.5)
            self.project = nn.Linear(embed_dim,token_dim * 3 * 3)

        self.num_patches = (img_size // (4 * 2 * 2)) * (img_size // (4 * 2 * 2))  # there are 3 sfot split, stride are 4,2,2 seperately

    def forward(self, x):   # [1,256, 64]
        x = self.project(x).transpose(1, 2)  # [1,256,576] -> [1, 576, 256]

        # CTformer module C
        x = self.soft_split2(x)  # [1, 64, 32,32]
        x = torch.roll(x, shifts=(-2, -2), dims=(-1, -2))
        t1c_2 = rearrange(x,'b c h w -> b c (h w)').transpose(1,2)   # [1, 32*32, 64]
        x = t1c_2
        x = self.attention2(x).transpose(1, 2)  #[1,1024, 576] -> [1,576, 1024]
        
        # CTformer module D
        x = self.soft_split1(x)  # [1, 64, 64, 64]
        x = torch.roll(x, shifts=(-2, -2), dims=(-1, -2))
        t1c_1 = rearrange(x,'b c h w -> b c (h w)').transpose(1,2) # [1, 64*64, 64]
        x = t1c_1
        x = self.attention1(x).transpose(1, 2)  # [1, 4096, 49] -> [1, 49, 4096]
        
        # Detokenization
        x = self.soft_split0(x)  # [1, 1, 256, 256]

        return x, t1c_1, t1c_2

class decoder_ctf(nn.Module):
    """
    CTformer decoding module
    """
    def __init__(self, img_size=256, tokens_type='transformer', in_chans=1, embed_dim=256, token_dim=64, kernel=32,
                 stride=32):
        super(decoder_ctf, self).__init__()

        if tokens_type == 'transformer':
            print('adopt transformer encoder for tokens-to-token')
            self.soft_split0 = nn.Fold((256, 256), kernel_size=(7, 7), stride=(4, 4), padding=(2, 2))
            self.soft_split1 = nn.Fold((64, 64), kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
            self.soft_split2 = nn.Fold((32, 32), kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))

            self.attention1 = Token_transformer(dim=token_dim*3, in_dim=in_chans * 7 * 7, num_heads=1, mlp_ratio=1.0)
            self.attention2 = Token_transformer(dim=token_dim*3, in_dim=token_dim * 3 * 3, num_heads=1, mlp_ratio=1.0)
            self.project = nn.Linear(embed_dim, token_dim * 3 * 3)
        elif tokens_type == 'performer':
            # print('adopt performer encoder for tokens-to-token')
            self.soft_split0 = nn.Fold((256, 256), kernel_size=(7, 7), stride=(4, 4), padding=(2, 2))
            self.soft_split1 = nn.Fold((64, 64), kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
            self.soft_split2 = nn.Fold((32, 32), kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))

            self.attention1 = Token_performer(dim=token_dim*3, in_dim=in_chans * 7 * 7, kernel_ratio=0.5)
            self.attention2 = Token_performer(dim=token_dim*3, in_dim=token_dim * 3 * 3, kernel_ratio=0.5)
            self.project = nn.Linear(embed_dim, token_dim * 3 * 3)

    def forward(self, cts, t1, t1cs): # [1,256, 64]
        x = self.project(cts).transpose(1, 2)    # [1,256,576] -> [1, 576, 256]

        # CTformer module C
        x = self.soft_split2(x)     # [1, 64, 32,32]
        x = torch.roll(x, shifts=(-2, -2), dims=(-1, -2))
        ct_2 = rearrange(x, 'b c h w -> b c (h w)').transpose(1, 2)      # [1, 32*32, 64]
        x = torch.cat((ct_2, t1[2], t1cs[2]), dim=2)    # [1, 32*32, 64*5]
        x = self.attention2(x).transpose(1, 2)   # [1,1024, 576] -> [1,576, 1024]

        # CTformer module D
        x = self.soft_split1(x)    # [1, 64, 64, 64]
        x = torch.roll(x, shifts=(-2, -2), dims=(-1, -2))
        ct_1 = rearrange(x, 'b c h w -> b c (h w)').transpose(1, 2)    # [1, 64*64, 64]
        x = torch.cat((ct_1, t1[1], t1cs[1]), dim=2)  # [1, 64*64, 64*5]
        x = self.attention1(x).transpose(1, 2)    # [1, 4096, 49] -> [1, 49, 4096]
        # Detokenization
        x = self.soft_split0(x)  # [1, 1, 256, 256]

        return x

class CTformer(nn.Module):
    def __init__(self, img_size=256, tokens_type='performer', in_chans=1, num_classes=1000, embed_dim=768, depth=12,  ## transformer depth 12
                 num_heads=12, kernel=32, stride=32, mlp_ratio=4., qkv_bias=False, qk_scale=None, drop_rate=0.1, attn_drop_rate=0.1,
                 drop_path_rate=0.1, norm_layer=nn.LayerNorm, token_dim=1024):
        super(CTformer, self).__init__()
        self.num_classes = num_classes
        self.num_features = self.embed_dim = embed_dim  # num_features for consistency with other models

        # t1_encoder
        self.tokens_to_token = encoder(img_size=img_size, tokens_type=tokens_type, in_chans=in_chans, embed_dim=embed_dim, token_dim=token_dim,kernel=kernel, stride=stride)
        num_patches = self.tokens_to_token.num_patches

        self.cls_token = nn.Parameter(torch.zeros(1, 1, embed_dim))
        self.pos_embed = nn.Parameter(data=get_sinusoid_encoding(n_position=num_patches, d_hid=embed_dim), requires_grad=False)
        self.pos_drop = nn.Dropout(p=drop_rate)

        dpr = [x.item() for x in torch.linspace(0, drop_path_rate, depth)]  # stochastic depth decay rule
        self.blocks = nn.ModuleList([
            Block(
                dim=embed_dim, num_heads=num_heads, mlp_ratio=mlp_ratio, qkv_bias=qkv_bias, qk_scale=qk_scale,
                drop=drop_rate, attn_drop=attn_drop_rate, drop_path=dpr[i], norm_layer=norm_layer)
            for i in range(depth)])
        self.norm = norm_layer(embed_dim)

        # CTformer decoder
        self.decoder1 = decoder_t1c(img_size=img_size, tokens_type=tokens_type, in_chans=in_chans, embed_dim=embed_dim,
                               token_dim=token_dim, kernel=kernel, stride=stride)
        self.decoder2 = decoder_ctf(img_size=img_size, tokens_type=tokens_type, in_chans=in_chans, embed_dim=embed_dim,
                               token_dim=token_dim, kernel=kernel, stride=stride)
        # self.head = nn.Linear(embed_dim, num_classes) if num_classes > 0 else nn.Identity()

        trunc_normal_(self.cls_token, std=.02)
        self.apply(self._init_weights)

    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            trunc_normal_(m.weight, std=.02)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)

    @torch.jit.ignore
    def no_weight_decay(self):
        return {'cls_token'}

    def get_classifier(self):
        return self.head

    def reset_classifier(self, num_classes, global_pool=''):
        self.num_classes = num_classes
        self.head = nn.Linear(self.embed_dim, num_classes) if num_classes > 0 else nn.Identity()

    def forward(self, x):
        # encoder_share
        t1 = self.tokens_to_token(x)
        x = t1[0] + self.pos_embed
        x = self.pos_drop(x)
        i = 0
        for blk in self.blocks: # only one intermediate transformer block
            i += 1
            x = blk(x)
        share = self.norm(x)

        # decoder_t1c
        i = 0
        t1cs = share
        for blk in self.blocks:
            i += 1
            t1cs = blk(t1cs)
        t1cs = self.norm(t1cs)
        t1cs = self.decoder1(t1cs)


        # decoder_ct
        i = 0
        cts = share
        for blk in self.blocks:
            i += 1
            cts = blk(cts)
        cts = self.norm(cts)
        ct = self.decoder2(cts, t1, t1cs)

        return t1cs[0], ct
`

**Comment by Joker-ZXR** [comment]
Thank you for your reply @wdayang. This is my model code.I made some modifications to the model. The input images of the task were T1 sequences of MRI, and the objective was to generate T1c sequences of MRI and CT.
`class encoder(nn.Module):
    """
    CTformer encoding module
    """
    def __init__(self, img_size=256, tokens_type='performer', in_chans=1, embed_dim=256, token_dim=64, kernel=32, stride=32):
        super(encoder, self).__init__()

        if tokens_type == 'transformer':
            print('adopt transformer encoder for tokens-to-token')
            self.soft_split0 = nn.Unfold(kernel_size=(7, 7), stride=(4, 4), padding=(2, 2))
            self.soft_split1 = nn.Unfold(kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
            self.soft_split2 = nn.Unfold(kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))

            self.attention1 = Token_transformer(dim=in_chans*7*7, in_dim=token_dim, num_heads=1, mlp_ratio=1.0)
            self.attention2 = Token_transformer(dim=token_dim*3*3, in_dim=token_dim, num_heads=1, mlp_ratio=1.0)
            self.project = nn.Linear(token_dim * 3 * 3, embed_dim)

        elif tokens_type == 'performer':
            # print('adopt performer encoder for tokens-to-token')
            self.soft_split0 = nn.Unfold(kernel_size=(7, 7), stride=(4, 4), padding=(2, 2))
            self.soft_split1 = nn.Unfold(kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
            self.soft_split2 = nn.Unfold(kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))

            self.attention1 = Token_performer(dim=in_chans*7*7, in_dim=token_dim, kernel_ratio=0.5)
            self.attention2 = Token_performer(dim=token_dim*3*3, in_dim=token_dim, kernel_ratio=0.5)
            self.project = nn.Linear(token_dim * 3 * 3, embed_dim)
        self.num_patches = (img_size // (4 * 2 * 2)) * (img_size // (4 * 2 * 2))  # there are 3 sfot split, stride are 4,2,2 seperately
        
    def forward(self, x):  # input[1,1,256,256]
        # Tokenization
        x = self.soft_split0(x)   # [1, 7*7, 64*64])
        
        # CTformer module A
        x = self.attention1(x.transpose(1, 2))  # [1, 64*64, 7*7] ->[1, 64*64, 64]
        t1_1 = x  # [1, 64*64, 64]
        B, new_HW, C = x.shape
        x = x.transpose(1,2).reshape(B, C, int(np.sqrt(new_HW)), int(np.sqrt(new_HW))) # [1, 64, 64, 64]
        x = torch.roll(x, shifts=(2, 2), dims=(2, 3))  # shift some positionts
        x = self.soft_split1(x)   # [1, 3*3*64=576, 64*64=4096]
        
        # CTformer module B
        x = self.attention2(x.transpose(1, 2))  # [1, 32*32, 3*3*64] ->[1, 32*32, 64]
        t1_2 = x  # [1, 32*32, 64]
        B, new_HW, C = x.shape
        x = x.transpose(1, 2).reshape(B, C, int(np.sqrt(new_HW)), int(np.sqrt(new_HW))) # [1, 64, 32, 32]
        x = torch.roll(x, shifts=(2, 2), dims=(2, 3))  # shift back position
        x = self.soft_split2(x)    # [1, 3*3*64=576, 16*16=256]

        x = self.project(x.transpose(1, 2))  # no projection[1,16*16=256, 64]
        return x, t1_1, t1_2  # res0,res2
    
class decoder_t1c(nn.Module):
    """
    CTformer decoding module
    """
    def __init__(self, img_size=256, tokens_type='performer', in_chans=1, embed_dim=256, token_dim=64, kernel=32, stride=32):
        super(decoder_t1c, self).__init__()

        if tokens_type == 'transformer':
            print('adopt transformer encoder for tokens-to-token')
            self.soft_split0 = nn.Fold((256,256),kernel_size=(7, 7), stride=(4, 4), padding=(2, 2))
            self.soft_split1 = nn.Fold((64,64),kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
            self.soft_split2 = nn.Fold((32,32),kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))

            self.attention1 = Token_transformer(dim=token_dim, in_dim=in_chans*7*7, num_heads=1, mlp_ratio=1.0)
            self.attention2 = Token_transformer(dim=token_dim, in_dim=token_dim*3*3, num_heads=1, mlp_ratio=1.0)
            self.project = nn.Linear(embed_dim,token_dim * 3 * 3)
        elif tokens_type == 'performer':
            #print('adopt performer encoder for tokens-to-token')
            self.soft_split0 = nn.Fold((256,256),kernel_size=(7, 7), stride=(4, 4), padding=(2, 2))
            self.soft_split1 = nn.Fold((64,64),kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
            self.soft_split2 = nn.Fold((32,32),kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))

            self.attention1 = Token_performer(dim=token_dim, in_dim=in_chans*7*7, kernel_ratio=0.5)
            self.attention2 = Token_performer(dim=token_dim, in_dim=token_dim*3*3, kernel_ratio=0.5)
            self.project = nn.Linear(embed_dim,token_dim * 3 * 3)

        self.num_patches = (img_size // (4 * 2 * 2)) * (img_size // (4 * 2 * 2))  # there are 3 sfot split, stride are 4,2,2 seperately

    def forward(self, x):   # [1,256, 64]
        x = self.project(x).transpose(1, 2)  # [1,256,576] -> [1, 576, 256]

        # CTformer module C
        x = self.soft_split2(x)  # [1, 64, 32,32]
        x = torch.roll(x, shifts=(-2, -2), dims=(-1, -2))
        t1c_2 = rearrange(x,'b c h w -> b c (h w)').transpose(1,2)   # [1, 32*32, 64]
        x = t1c_2
        x = self.attention2(x).transpose(1, 2)  #[1,1024, 576] -> [1,576, 1024]
        
        # CTformer module D
        x = self.soft_split1(x)  # [1, 64, 64, 64]
        x = torch.roll(x, shifts=(-2, -2), dims=(-1, -2))
        t1c_1 = rearrange(x,'b c h w -> b c (h w)').transpose(1,2) # [1, 64*64, 64]
        x = t1c_1
        x = self.attention1(x).transpose(1, 2)  # [1, 4096, 49] -> [1, 49, 4096]
        
        # Detokenization
        x = self.soft_split0(x)  # [1, 1, 256, 256]

        return x, t1c_1, t1c_2

class decoder_ctf(nn.Module):
    """
    CTformer decoding module
    """
    def __init__(self, img_size=256, tokens_type='transformer', in_chans=1, embed_dim=256, token_dim=64, kernel=32,
                 stride=32):
        super(decoder_ctf, self).__init__()

        if tokens_type == 'transformer':
            print('adopt transformer encoder for tokens-to-token')
            self.soft_split0 = nn.Fold((256, 256), kernel_size=(7, 7), stride=(4, 4), padding=(2, 2))
            self.soft_split1 = nn.Fold((64, 64), kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
            self.soft_split2 = nn.Fold((32, 32), kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))

            self.attention1 = Token_transformer(dim=token_dim*3, in_dim=in_chans * 7 * 7, num_heads=1, mlp_ratio=1.0)
            self.attention2 = Token_transformer(dim=token_dim*3, in_dim=token_dim * 3 * 3, num_heads=1, mlp_ratio=1.0)
            self.project = nn.Linear(embed_dim, token_dim * 3 * 3)
        elif tokens_type == 'performer':
            # print('adopt performer encoder for tokens-to-token')
            self.soft_split0 = nn.Fold((256, 256), kernel_size=(7, 7), stride=(4, 4), padding=(2, 2))
            self.soft_split1 = nn.Fold((64, 64), kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
            self.soft_split2 = nn.Fold((32, 32), kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))

            self.attention1 = Token_performer(dim=token_dim*3, in_dim=in_chans * 7 * 7, kernel_ratio=0.5)
            self.attention2 = Token_performer(dim=token_dim*3, in_dim=token_dim * 3 * 3, kernel_ratio=0.5)
            self.project = nn.Linear(embed_dim, token_dim * 3 * 3)

    def forward(self, cts, t1, t1cs): # [1,256, 64]
        x = self.project(cts).transpose(1, 2)    # [1,256,576] -> [1, 576, 256]

        # CTformer module C
        x = self.soft_split2(x)     # [1, 64, 32,32]
        x = torch.roll(x, shifts=(-2, -2), dims=(-1, -2))
        ct_2 = rearrange(x, 'b c h w -> b c (h w)').transpose(1, 2)      # [1, 32*32, 64]
        x = torch.cat((ct_2, t1[2], t1cs[2]), dim=2)    # [1, 32*32, 64*5]
        x = self.attention2(x).transpose(1, 2)   # [1,1024, 576] -> [1,576, 1024]

        # CTformer module D
        x = self.soft_split1(x)    # [1, 64, 64, 64]
        x = torch.roll(x, shifts=(-2, -2), dims=(-1, -2))
        ct_1 = rearrange(x, 'b c h w -> b c (h w)').transpose(1, 2)    # [1, 64*64, 64]
        x = torch.cat((ct_1, t1[1], t1cs[1]), dim=2)  # [1, 64*64, 64*5]
        x = self.attention1(x).transpose(1, 2)    # [1, 4096, 49] -> [1, 49, 4096]
        # Detokenization
        x = self.soft_split0(x)  # [1, 1, 256, 256]

        return x

class CTformer(nn.Module):
    def __init__(self, img_size=256, tokens_type='performer', in_chans=1, num_classes=1000, embed_dim=768, depth=12,  ## transformer depth 12
                 num_heads=12, kernel=32, stride=32, mlp_ratio=4., qkv_bias=False, qk_scale=None, drop_rate=0.1, attn_drop_rate=0.1,
                 drop_path_rate=0.1, norm_layer=nn.LayerNorm, token_dim=1024):
        super(CTformer, self).__init__()
        self.num_classes = num_classes
        self.num_features = self.embed_dim = embed_dim  # num_features for consistency with other models

        # t1_encoder
        self.tokens_to_token = encoder(img_size=img_size, tokens_type=tokens_type, in_chans=in_chans, embed_dim=embed_dim, token_dim=token_dim,kernel=kernel, stride=stride)
        num_patches = self.tokens_to_token.num_patches

        self.cls_token = nn.Parameter(torch.zeros(1, 1, embed_dim))
        self.pos_embed = nn.Parameter(data=get_sinusoid_encoding(n_position=num_patches, d_hid=embed_dim), requires_grad=False)
        self.pos_drop = nn.Dropout(p=drop_rate)

        dpr = [x.item() for x in torch.linspace(0, drop_path_rate, depth)]  # stochastic depth decay rule
        self.blocks = nn.ModuleList([
            Block(
                dim=embed_dim, num_heads=num_heads, mlp_ratio=mlp_ratio, qkv_bias=qkv_bias, qk_scale=qk_scale,
                drop=drop_rate, attn_drop=attn_drop_rate, drop_path=dpr[i], norm_layer=norm_layer)
            for i in range(depth)])
        self.norm = norm_layer(embed_dim)

        # CTformer decoder
        self.decoder1 = decoder_t1c(img_size=img_size, tokens_type=tokens_type, in_chans=in_chans, embed_dim=embed_dim,
                               token_dim=token_dim, kernel=kernel, stride=stride)
        self.decoder2 = decoder_ctf(img_size=img_size, tokens_type=tokens_type, in_chans=in_chans, embed_dim=embed_dim,
                               token_dim=token_dim, kernel=kernel, stride=stride)
        # self.head = nn.Linear(embed_dim, num_classes) if num_classes > 0 else nn.Identity()

        trunc_normal_(self.cls_token, std=.02)
        self.apply(self._init_weights)

    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            trunc_normal_(m.weight, std=.02)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)

    @torch.jit.ignore
    def no_weight_decay(self):
        return {'cls_token'}

    def get_classifier(self):
        return self.head

    def reset_classifier(self, num_classes, global_pool=''):
        self.num_classes = num_classes
        self.head = nn.Linear(self.embed_dim, num_classes) if num_classes > 0 else nn.Identity()

    def forward(self, x):
        # encoder_share
        t1 = self.tokens_to_token(x)
        x = t1[0] + self.pos_embed
        x = self.pos_drop(x)
        i = 0
        for blk in self.blocks: # only one intermediate transformer block
            i += 1
            x = blk(x)
        share = self.norm(x)

        # decoder_t1c
        i = 0
        t1cs = share
        for blk in self.blocks:
            i += 1
            t1cs = blk(t1cs)
        t1cs = self.norm(t1cs)
        t1cs = self.decoder1(t1cs)


        # decoder_ct
        i = 0
        cts = share
        for blk in self.blocks:
            i += 1
            cts = blk(cts)
        cts = self.norm(cts)
        ct = self.decoder2(cts, t1, t1cs)

        return t1cs[0], ct`

**Comment by wdayang** [comment]
Hi @Joker-ZXR , sorry for late reply. I think you can use MRI image to generate MRI image by directly using our model, but if you want to generate both MRI and CT images from MRI images, I think it may not work. One of the possible reasons might be, the encoder-decoder architecture assumes that similar level feature maps has similar information. Maybe you need to add some more modules for the transformation between MRI and CT images? I am not sure, just a possible solution. 

Best,
Dayang

**Comment by Joker-ZXR** [comment]
Thank you for your reply.
I think so too. I think the T2T approach is a little too difficult for generating tasks. Personally, I understand that its architecture is to expand the image from another dimension to realize the local information integration of convolution and the long information integration of self-attention. More is to retain the original image information, including local and global. So I think maybe T2T is better suited for rebuilding tasks than for generating tasks. I also looked into it, and T2T seems to be used for classification. And your article is used for reconstruction for the first time, which I think is a very appropriate idea.

Thank you very much for your answer, which makes me have a further understanding of T2T.

**Comment by wdayang** [comment]
Thanks for your interest and acknowledgment. I agree with your point, the T2T is more to retain the original information from the input image. The first T2T paper is for the classification task. But after the T2T process, they have plenty of transformer blocks for feature inference and learning high-level information. For your task, I think you may need to add some prior knowledge on the transformation between the MRI and CT image. Hope you good luck. Thanks.

Best,
Dayang
