### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by wxslby** [wdayang/CTformer#9]
作者您好，感谢您出色的工作。在作为成对图像对处理时，我参考了您给的REDCNN的数据准备工作，但是我下载的数据集和SSinyu给出的截图好像有些不同，我使用了AAPM中Training_Image_Data\3mm B30\full_3mm及quarter_3mm，作为一名小白，不清楚使用的数据集是否是常规数据集。请问是我使用的数据集有问题还是SSinyu的笔误呢？
![屏幕截图 2022-10-20 101125](https://user-images.githubusercontent.com/81366534/196840475-f11f870d-5ff4-4dd2-b08d-ef606c85f4a5.png)
![Inked屏幕截图 2022-10-20 101056](https://user-images.githubusercontent.com/81366534/196840520-d9afb42c-bc74-46e3-8762-c66466fc87af.jpg)

**Comment by wdayang** [comment]
不好意思，我这边已经没有原始IMA数据了，我也不是百分百确定对不对，你可以先跑一下prep.py代码，看能不能出来正确的npy文件。


获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Kerri-lovely ***@***.***>
Sent: Wednesday, October 19, 2022 10:21:03 PM
To: wdayang/CTformer ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wdayang/CTformer] 数据集 (Issue #9)


作者您好，感谢您出色的工作。在作为成对图像对处理时，我参考了您给的REDCNN的数据准备工作，但是我下载的数据集和SSinyu给出的截图好像有些不同，我使用了AAPM中Training_Image_Data\3mm B30\full_3mm及quarter_3mm，作为一名小白，不清楚使用的数据集是否是常规数据集。请问是我使用的数据集有问题还是SSinyu的笔误呢？
[屏幕截图 2022-10-20 101125]<https://user-images.githubusercontent.com/81366534/196840475-f11f870d-5ff4-4dd2-b08d-ef606c85f4a5.png>
[Inked屏幕截图 2022-10-20 101056]<https://user-images.githubusercontent.com/81366534/196840520-d9afb42c-bc74-46e3-8762-c66466fc87af.jpg>

―
